[build-system]
requires = [
    "setuptools",
    "setuptools_scm",
]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]
include = ["*"]

[tool.setuptools]
include-package-data = false # force explicit declaration of data (disable automatic inclusion)

[tool.setuptools.package-data]
"openalea.vmapplet" = ["data/markov/*", "data/markov/**/*", "data/lpy/*", "data/trunk/*"]

# enable dynamic version based on git tags
[tool.setuptools_scm]
# Format version to ease alignment with conda/meta.yaml tag-based versioning
fallback_version = "0.1.0.dev0"
version_scheme = "guess-next-dev"
local_scheme = "no-local-version"

[project]
name = "openalea.vmapplet"
authors = [
  { name = "Thomas Cokelaer" },
  { name = "Colin Smith" },
  { name = "Jan Vaillant" },
  { name = "Frederic Boudon" }
]
description = "Apple Tree simulation using Markov Chains based on MAppleT"
readme = "README.md"
license = "CECILL-C"
license-files = ["LICEN[CS]E*"]
requires-python = ">=3.10"
dynamic = ["version"]
keywords = ["openalea", "jupyter", "tree", "MTG", "lpy", "plantgl", "3D"]
classifiers = [
  "Intended Audience :: Science/Research",
  "Intended Audience :: Developers",
  "Operating System :: OS Independent",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
  "Topic :: Scientific/Engineering",
]

dependencies = [
    "jupyterlab",
    "jupyterlab_widgets",
    "ipywidgets",
    "toml",
    "scipy",
    "xlrd",
    "numpy",
    "flake8",
    "mypy",
    "black",
]


[project.optional-dependencies]
test = [
  "pytest",
  "nbmake",
]
dev = [
  "pytest >=6",
  "pytest-cov >=3",
]
doc = [
  "sphinx-autobuild",
  "pydata-sphinx-theme",
  "myst-parser",
  "sphinx-favicon",
  "ipykernel",
  "sphinx-copybutton",
  "ipython_genutils",
  "nbsphinx",
  "pgljupyter",
]

# section specific to conda-only distributed package (not used by pip yet)
[tool.conda.environment]
channels = [
  "openalea3",
  "conda-forge"
]
dependencies = [
    "openalea.lpy",
    "openalea.plantgl",
    "openalea.mtg",
    "matplotlib-base",
]

[project.urls]
Homepage = "https://vmapplet.readthedocs.io/"
"Bug Tracker" = "https://github.com/openalea/vmapplet/issues"
Discussions = "https://github.com/openalea/vmapplet/discussions"
Changelog = "https://github.com/openalea/vmapplet/releases"
